# Generated by Django 3.0.6 on 2020-06-09 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FilterDemo',
            new_name='FilterModel',
        ),
    ]
